export const userData = [
  {
    name: "Monday",
    "Active User": 4000,
  },
  {
    name: "Tuesday",
    "Active User": 1000,
  },
  {
    name: "Wednesday",
    "Active User": 5000,
  },
  {
    name: "Thursday",
    "Active User": 2000,
  },
  {
    name: "Friday",
    "Active User": 3000,
  },
  {
    name: "Saturday",
    "Active User": 2000,
  },
  {
    name: "Sunday",
    "Active User": 4000,
  },
];
export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Eyes",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Eyes",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Eyes",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "False",
    transaction: "Cancer",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "False",
    transaction: "Cancer",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "False",
    transaction: "Cancer",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Cancer",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Trauma",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "True",
    transaction: "Trauma",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar: "https://i.ibb.co/Nmmczqx/patient-icon-png-26.png",
    email: "jon@gmail.com",
    status: "False",
    transaction: "Trauma",
  },
];

export const HouseRows = [
  {
    id: 1,
    ownername: "Jon Snow",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "7",
  },
  {
    id: 2,
    ownername: "Kiki toure",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "5",
  },
  {
    id: 3,
    ownername: "Iman shumpert",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "3",
  },
  {
    id: 4,
    ownername: "Jon Snow",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "7",
  },
  {
    id: 5,
    ownername: "Kiki toure",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "5",
  },
  {
    id: 6,
    ownername: "Iman shumpert",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "3",
  },

  {
    id: 7,
    ownername: "Jon Snow",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "7",
  },
  {
    id: 8,
    ownername: "Kiki toure",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "5",
  },
  {
    id: 9,
    ownername: "Iman shumpert",
    address: "Kigali",
    avatar: "https://i.ibb.co/2sGkcvZ/homesmall.png",
    phone: "+250788730199",
    new: "True",
    people: "3",
  },
];
